'use strict';
const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');

const REPO_ROOT = path.resolve(__dirname, '..');
const adapter = require(path.join(REPO_ROOT, 'bin/lib/runtime-codex.cjs'));
const { installRuntime } = require(path.join(REPO_ROOT, 'bin/lib/install.cjs'));
const { readState } = require(path.join(REPO_ROOT, 'bin/lib/install-state.cjs'));
const { version: OTO_VERSION } = require(path.join(REPO_ROOT, 'package.json'));

function tmpDir(t, prefix) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), prefix));
  t.after(() => fs.rmSync(dir, { recursive: true, force: true }));
  return dir;
}

test('D-10 install.cjs calls adapter.emitDerivedFiles after copy pass and records returned entries', async (t) => {
  const configDir = tmpDir(t, 'oto-codex-install-');
  const projectRoot = tmpDir(t, 'oto-codex-project-');
  const calls = [];

  const stubAdapter = {
    ...adapter,
    onPostInstall() {},
    async emitDerivedFiles(ctx) {
      calls.push(ctx);
      const target = path.join(ctx.configDir, 'agents', 'derived.toml');
      fs.mkdirSync(path.dirname(target), { recursive: true });
      fs.writeFileSync(target, '# generated by wiring test\n');
      return [{ path: 'agents/derived.toml', sha256: '0'.repeat(64) }];
    },
  };

  await installRuntime(stubAdapter, {
    flags: { configDir, runtimes: ['codex'] },
    repoRoot: REPO_ROOT,
    projectRoot,
  });

  assert.equal(calls.length, 1);
  assert.equal(calls[0].configDir, configDir);
  assert.equal(calls[0].repoRoot, REPO_ROOT);
  assert.equal(calls[0].otoVersion, OTO_VERSION);
  assert.equal(calls[0].projectRoot, projectRoot);

  const state = readState(path.join(configDir, 'oto/.install.json'));
  assert.ok(state.files.some((entry) => entry.path === 'agents/derived.toml' && entry.sha256 === '0'.repeat(64)));
});

test('D-10 codex adapter emits per-agent TOML files with sandbox and model profile resolution', async (t) => {
  const configDir = tmpDir(t, 'oto-codex-derived-');
  const projectRoot = tmpDir(t, 'oto-codex-project-config-');
  fs.mkdirSync(path.join(projectRoot, '.oto'), { recursive: true });
  fs.writeFileSync(path.join(projectRoot, '.oto/config.json'), JSON.stringify({ model_profile: 'opus' }));

  const entries = await adapter.emitDerivedFiles({
    configDir,
    repoRoot: REPO_ROOT,
    otoVersion: OTO_VERSION,
    projectRoot,
  });

  const target = path.join(configDir, 'agents/oto-executor.toml');
  const text = fs.readFileSync(target, 'utf8');
  assert.ok(entries.some((entry) => entry.path === 'agents/oto-executor.toml'));
  assert.match(text, /^# managed by oto v/m);
  assert.match(text, /^sandbox_mode = "workspace-write"$/m);
  assert.match(text, /^model = "gpt-5\.4"$/m);
  assert.match(text, /^model_reasoning_effort = "xhigh"$/m);
  assert.equal(text.includes('@~/.claude/'), false);
});
