'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { render, validateFencePairing } = require('../bin/lib/instruction-file.cjs');
const { version: OTO_VERSION } = require('../package.json');

const REPO_ROOT = path.resolve(__dirname, '..');
const ctx = {
  otoVersion: OTO_VERSION,
  repoUrl: 'https://github.com/OTOJulian/oto-hybrid-framework',
  generatedHeader: '<!-- Generated by scripts/render-instruction-files.cjs from oto/templates/instruction-file.md. Do not edit. -->',
};

test('D-03 regen-diff: render(claude) byte-equals committed CLAUDE.md', () => {
  const rendered = render('claude', ctx);
  const committed = fs.readFileSync(path.join(REPO_ROOT, 'CLAUDE.md'), 'utf8');
  assert.strictEqual(rendered, committed, 'CLAUDE.md drift - run: node scripts/render-instruction-files.cjs');
});

test('D-03 regen-diff: render(codex) byte-equals committed AGENTS.md', () => {
  const rendered = render('codex', ctx);
  const committed = fs.readFileSync(path.join(REPO_ROOT, 'AGENTS.md'), 'utf8');
  assert.strictEqual(rendered, committed, 'AGENTS.md drift - run: node scripts/render-instruction-files.cjs');
});

test('D-03 regen-diff: render(gemini) byte-equals committed GEMINI.md', () => {
  const rendered = render('gemini', ctx);
  const committed = fs.readFileSync(path.join(REPO_ROOT, 'GEMINI.md'), 'utf8');
  assert.strictEqual(rendered, committed, 'GEMINI.md drift - run: node scripts/render-instruction-files.cjs');
});

test('D-02 fence pairing: unclosed runtime fence throws (Pitfall 7)', () => {
  assert.throws(() => validateFencePairing('<!-- runtime:codex -->\nbody (no close)\n'), /codex/);
});

test('D-02 token substitution: {{otoVersion}} replaced from ctx', () => {
  const rendered = render('claude', { ...ctx, otoVersion: 'TEST-V' });
  assert.ok(rendered.includes('TEST-V'), 'expected TEST-V in rendered output');
  assert.ok(!rendered.includes('{{otoVersion}}'), 'expected {{otoVersion}} fully substituted');
});
